name: Detect changes
description:

inputs:
  paths:
    required: true
    description: paths that trigger the build
  branch_tag:
    required: true
    description: branch tag for the image
  before:
    required: true
    description: before sha
  is_forced:
    required: true
    description: github.event.forced

outputs:
  tag:
    description:
    value: ${{ steps.tag.outputs.tag }}
  changed:
    description:
    value: ${{ steps.tag.outputs.changed }}

runs:
  using: "composite"
  steps:
    - id: changes-push
      if: inputs.is_forced == "false"
      uses: tj-actions/changed-files@v45
      with:
        files: ${{ inputs.paths }}

    - id: changes-branch
      if: inputs.is_forced == "false" && ! steps.changes-push.outputs.any_changed
      uses: tj-actions/changed-files@v45
      with:
        files: ${{ inputs.paths }}

    - id: tag
      if: ${{ ! failure() }}
      env:
        sha: ${{ github.sha }}
        is_forced: ${{ inputs.is_forced }}
        push_changed: ${{ steps.changes-push.outputs.any_changed }}
        branch_changed: ${{ steps.changes-branch.outputs.any_changed }}
        default: ${{ github.event.repository.default_branch }}
      run: .github/determine-tag.sh >> "${GITHUB_OUTPUT}"
      shell: sh
