name: Detect changes
description:
inputs:
  paths:
    required: true
    description: paths that trigger the build
  branch_tag:
    required: true
    description:

outputs:
  tag:
    description:
    value: ${{ steps.tag.outputs.tag }}
  changed:
    description:
    value: ${{ steps.changes.outputs.any_changed }}

runs:
  using: "composite"
  steps:
    - id: changes
      uses: tj-actions/changed-files@v35
      with:
        files: ${{ inputs.paths }}

    - name: Show changes
      env:
        changed: ${{ steps.changes.outputs.all_changed_files }}
      # TBD: this can easily go out of argv limits
      run: printf "%s\n" $changed
      shell: sh

    - id: tag
      env:
        sha: ${{ github.sha }}
        any_changed: ${{ steps.base-debian.outputs.any_changed }}
      run: |
        printf "tag=" >> "${GITHUB_OUTPUT}"
        ${any_changed} && {
          echo "$sha" >> "${GITHUB_OUTPUT}"
        } || {
          echo "$branch_tag" >> "${GITHUB_OUTPUT}"
        }
      shell: sh
