name: Trigger Workflow

inputs:
  token:
    required: true
    description: github token
  workflow:
    required: true
    description: Workflow filename

runs:
  using: "composite"
  steps:
    - env:
        repo: ${{ github.repository }}
        token: ${{ inputs.token }}
        sha: ${{ github.sha }}
        URL:  https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ inputs.workflow }}/dispatches
        ref: ${{ toJSON(github.ref) }}
        before: ${{ toJSON(github.event.before) }}
        after: ${{ toJSON(github.event.after) }}
      shell: sh
      run: |
          curl \
            -X POST $URL \
            -H "Authorization: Bearer $token" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "ref": '${ref}',
              "inputs": {
                "before": '${before}',
                "after": '${after}',
              }}'
