name: GHA Testing - Common Workflow

on:
  workflow_call:
    inputs:
      job_id:
        required: true
        type: string

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  # Can't have ${{ github.workflow }} here as that is inherited from the
  # calling workflow so it causes a deadlock as main workflow needs called
  # workflow but called workflow can't run due to shared concurrency group.
  group: common-${{ github.ref }}-
  # Can't use cancel in progress as that cancels the entire calling workflow.
  # But at least this will linearize the common workflow so only the first one
  # actually builds and the rest will use caches.
  # It will increase the total runtime by those wait times but might be worth.
  cancel-in-progress: false

jobs:
  build-base-debian:
    if: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-debian
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

