name: GHA Testing - Common Workflow

on:
  workflow_call:
    inputs:
      job_id:
        required: true
        type: string

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  # Can't have ${{ github.workflow }} here as that is inherited from the
  # calling workflow so it causes a deadlock as main workflow needs called
  # workflow but called workflow can't run due to shared concurrency group.
  group: common-${{ github.ref }}-
  cancel-in-progress: true

jobs:
  build-base-debian:
    if: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-debian
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

