name: GHA Testing - Main Workflow

on: [push]

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      # It would make sense to run these within the image build job so we can
      # refer to outputs like:
      # - needs.base-debian.outputs.tag
      # - needs.base-debian.outputs.is_changed
      #
      # However, then we would'be wasting checkouts just to determine there is
      # no change and set the tag.
      base-debian-tag: ${{ steps.base-debian-tag.outputs.tag }}
      base-debian: ${{ steps.base-debian.outputs.any-changed }}
    steps:
      - uses: actions/checkout@v4

      - id: base-debian
        uses: tj-actions/changed-files@v35
        with:
          files: |
            container/base-debian/**

      - name: Show base-debian changed files
        env:
          changed: ${{ steps.base-debian.outputs.all_changed_files }}
        # TBD: this can easily go out of argv limits
        run: printf "%s\n" $changed
        shell: sh

      - id: base-debian-tag
        env:
          ref: ${{ github.ref_name }}
          sha: ${{ github.sha }}
          any_changed: ${{ steps.base-debian.outputs.any-changed }}
        run: |
          printf "tag=" >> "${GITHUB_OUTPUT}"
          ${any_changed} && {
            echo "$sha" >> "${GITHUB_OUTPUT}"
          } || {
            echo "$ref" | sed 's#/#__#g' >> "${GITHUB_OUTPUT}"
          }

  build-base-debian:
    runs-on: ubuntu-latest
    needs:
      - analyze
    steps:
      - uses: actions/checkout@v4
        if: needs.analyze.outputs.base-debian
      - uses: "./.github/actions/build-image"
        if: needs.analyze.outputs.base-debian
        with:
          image: base-debian
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

  runtime-1:
    needs:
      - analyze
      - build-base-debian
    uses: ./.github/workflows/runtime-1.yaml
    with:
      base-debian-tag: ${{ needs.analyze.outputs.base-debian-tag }}
    secrets: inherit

  runtime-2:
    needs:
      - build-base-debian
    uses: ./.github/workflows/runtime-2.yaml
    secrets: inherit

