name: GHA Testing - Main Workflow

on: [push]

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      branch_tag: ${{ steps.branch-tag.outputs.branch_tag }}
      # It would make sense to run these within the image build job so we can
      # refer to outputs like:
      # - needs.base-debian.outputs.tag
      # - needs.base-debian.outputs.is_changed
      #
      # However, then we would'be wasting checkouts just to determine there is
      # no change and set the tag.
      base-debian-tag: ${{ steps.tags.outputs.base-debian_tag }}
      base-debian: ${{ steps.changes.outputs.base-debian_any_changed }}
      runtime-1: ${{ (steps.changes.outputs.runtime-1_any_changed || steps.changes.outputs.base-debian_any_changed) }}
    steps:
      # TBD: check if $ref_name exists in registry, otheriwse build.
      - uses: actions/checkout@v4

      - id: changes
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            base-debian:
              - containers/base-debian/**
            runtime-1:
              - containers/base-runtime-1/**

      - id: tags
        env:
          sha: ${{ github.sha }}
          ref_name: ${{ github.ref_name }}
          base_debian_changed: ${{ steps.changes.outputs.base-debian_any_changed }}
          runtime_1_changed: ${{ steps.changes.outputs.runtime-1_any_changed }} || ${{ steps.changes.outputs.base-debian_any_changed }}
        run: |
          function mk_output {
            local changed=$1
            local name=$2
            printf "%s=" $name >> "${GITHUB_OUTPUT}"
            $changed && {
              echo "$sha" >> "${GITHUB_OUTPUT}"
            } || {
              echo "$ref_name" >> "${GITHUB_OUTPUT}"
            }
          }
          set -x;
          mk_output ${base_debian_changed} base_debian;
          mk_output ${runtime_1_changed} runtime_1;

  build-base-debian:
    runs-on: ubuntu-latest
    needs:
      - analyze
    steps:
      - uses: actions/checkout@v4
        if: needs.analyze.outputs.base-debian == 'true'
      - uses: "./.github/actions/build-image"
        if: needs.analyze.outputs.base-debian == 'true'
        with:
          branch_tag: ${{ needs.analyze.outputs.branch_tag }}
          image: base-debian
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

  runtime-1:
    needs:
      - analyze
      - build-base-debian
    if: needs.analyze.outputs.runtime-1 == 'true'
    uses: ./.github/workflows/runtime-1.yaml
    with:
      branch_tag: ${{ needs.analyze.outputs.branch_tag }}
      base-debian-tag: ${{ needs.analyze.outputs.base-debian-tag }}
    secrets: inherit

  runtime-2:
    if: false
    needs:
      - build-base-debian
    uses: ./.github/workflows/runtime-2.yaml
    secrets: inherit

