name: GHA Testing - Main Workflow

on: [push]

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  analyze:
    runs-on: ubuntu-latest
    outputs:
      base-debian-tag: ${{ steps.base-debian-tag.outputs.tag }}
      base-debian-changed: ${{ steps.base-debian-changed-files.outputs.any-changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: base-debian-changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            container/base-debian/**

      - name: Show changed files
        env:
          changed: ${{ steps.changed-files.outputs.all_changed_files }}
        run: printf "%s\n" $changed
        shell: sh

      - id: base-debian-tag
        env:
          ref: ${{ github.ref }}
          sha: ${{ github.sha }}
          any_changed: ${{ steps.base-debian-changed-files.outputs.any-changed }}
        run: |
          printf "tag=" >> "${GITHUB_OUTPUT}"
          ${any_changed} && {
            echo "$sha" >> "${GITHUB_OUTPUT}"
          } || {
            echo "$ref" >> "${GITHUB_OUTPUT}"
          }

  build-base-debian:
    if: needs.analyze.outputs.base-debian-changed
    runs-on: ubuntu-latest
    needs:
      - analyze
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-debian
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

  runtime-1:
    needs:
      - analyze
      - build-base-debian
    uses: ./.github/workflows/runtime-1.yaml
    with:
      base-debian-tag: ${{ needs.analyze.outputs.base-debian-tag }}
    secrets: inherit

  runtime-2:
    needs:
      - build-base-debian
    uses: ./.github/workflows/runtime-2.yaml
    secrets: inherit

