name: GHA Testing - Main Workflow

on: [push]

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: echo ${{ github.workflow }} /// ${{ github.ref }}

  build-base-debian:
    if: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-debian
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

  runtime-1:
    needs:
      - build-base-debian
    uses: ./.github/workflows/runtime-1.yaml
    secrets: inherit

  runtime-2:
    needs:
      - build-base-debian
    uses: ./.github/workflows/runtime-2.yaml
    secrets: inherit

