name: GHA Testing - Runtime 2

on: push

concurrency:
  # Automatically cancel workflows if newer workflow started for the same
  # branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/common.yaml
    with:
      job_id: ${{ github.job }}
    secrets: inherit

  build-base-runtime-2:
    if: true
    runs-on: ubuntu-latest
    needs:
      - common
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/build-image"
        with:
          image: base-runtime-2
          registry: ghcr.io/${{ github.repository_owner }}
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GITHUB_TOKEN }}

  test-runtime-2:
    if: true
    runs-on: ubuntu-latest
    needs:
      - build-base-runtime-2
    container:
      image: ghcr.io/${{ github.repository }}_base-runtime-2:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: grep runtime-2 /mark
